name: OriEssentials
main: dev.oribuin.essentials.EssentialsPlugin
description: Modular essentials plugin for Spigot
api-version: '1.20'
version: '${version}'
author: Oribuin
softdepend:
  - PlaceholderAPI
